spring:
  application:
    name: youtuberef
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE:youtuberef}
    username: ${POSTGRESQL_USER:user}
    password: ${POSTGRESQL_PASSWORD:123456}
    hikari:
      pool-name: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

intergration:
  minio:
    access-key: ${MINIO_ACCESS_KEY:admin}
    secret-key: ${MINIO_SECRET_KEY:admin@2024}
    url: ${MINIO_URI:http://localhost:9000}

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
  jwtSecret: ${JWT_SECRET:MWM0NzE4MDk2MGQwMWFkNjZiNDQ5ZTJkMTJjYTE2N2M1YTFhY2E3M2UzMzBlMGMzZjU3OGVhMGQwMmQyZGM5OTgyODJlOWIwZGVhMzJkOTUzNTdlMjM4ZDIxMTk0YjgzNmEzNDNlMTBjZTMwMGMyNjgzYTc2ZTlmZjE5MzZkZmM=}
  # Token is valid 24 hours
  jwtExpiration: ${JWT_EXPIRE:86400}
  rememberMeExpiration: ${JWT_EXPIRE:2592000}


server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true